name: Daily AI Alignment Digest

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-digest:
    runs-on: ubuntu-latest
    env:
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      PYTHONPATH: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -c "import nltk; nltk.download(['punkt', 'punkt_tab'])"

    - name: Set up directories
      run: |
        mkdir -p data/posts
        mkdir -p data/digests

    - name: Generate digest
      run: python summarizer.py

    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/digests/
        git add ai_alignment_digest.log
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update digest for $(date +%Y-%m-%d)" && git push)
